---
- name: Configure Loopback Interface on Cisco Sandbox IOS XE
  hosts: iosxe
  gather_facts: no
  tasks:
    - name: Configure Loopback0 Interface
      ios_config:
        lines:
          - interface Loopback0
          - description Ansible Configured Loopback
          - ip address 10.10.10.50 255.255.255.0
        save_when: modified
