---
- name: List all interfaces on Cisco devices (IOS XR, NX-OS)
  hosts: all
  gather_facts: no

  tasks:
    - name: Show interfaces on IOS XR
      cisco.iosxr.iosxr_command:
        commands:
          - show ipv4 interface brief
      when: ansible_network_os == 'iosxr'
      register: xr_interfaces

    - name: Print IOS XR interfaces
      debug:
        var: xr_interfaces.stdout_lines[0]
      when: xr_interfaces is defined and inventory_hostname in groups['iosxr']

    - name: Show interfaces on NX-OS
      cisco.nxos.nxos_command:
        commands:
          - show interface brief
      when: ansible_network_os == 'nxos'
      register: nxos_interfaces

    - name: Print NX-OS interfaces
      debug:
        var: nxos_interfaces.stdout_lines[0]
      when: nxos_interfaces is defined and inventory_hostname in groups['nxos']
