---
- name: Playbook to retrieve interface facts
  hosts: all
  gather_facts: no

  tasks:
    - name: Retrieve interface facts
      cisco.ios.ios_facts:
        gather_subset: interfaces

    - name: Display interface information
      debug:
        var: ansible_net_interfaces
