---
- name: List all interfaces on Cisco router
  hosts: all
  gather_facts: no

  tasks:
    - name: Show all interfaces
      ios_command:
        commands:
          - show ip interface brief
      register: myinterfaces

    - name: Display interfaces
      debug:
        var: myinterfaces["stdout_lines"][0]
