---
- name: Show version on Cisco Sandbox IOS-XRv 9000 
  hosts: iosxr
  gather_facts: no
  tasks:
    - name: Run 'show version' command
      ansible.netcommon.cli_command:
        command: show version
      register: version_output

    - name: Print output
      debug:
        var: version_output.stdout_lines
