---
- name: Connect to Cisco IOS XE and run show version
  hosts: iosxe
  gather_facts: no
  tasks:
    - name: Show version
      ios_command:
        commands:
          - show version
      register: output

    - name: Display output
      debug:
        var: output.stdout
